#!/usr/bin/env ruby

require 'bundler'
Bundler.require

require_relative 'zero10dht.rb'

$zero10dht = Zero10DHT.connect
$redis = Redis.connect


def bench n
  require 'benchmark'

  Benchmark.bm do |x|
    x.report('set:') do
      for i in 1..n do
        $zero10dht.set(i, 'banana')
      end
    end
  end
end
def bench_redis n
  require 'benchmark'

  Benchmark.bm do |x|
    x.report('redis-set:') do
      for i in 1..n do
        $redis.set(i, 'banana')
      end
    end
  end
end

binding.pry
